name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Restore
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore --configuration Release --verbosity normal
    - name: Pack
      run: dotnet pack src/kickflip/kickflip.csproj --no-restore --configuration Release -o dist --verbosity normal
