name: Release

on:
  push:
    branches: [ "v*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Pack
      run: dotnet pack -o dist --verbosity normal
    - name: Publish
      run: dotnet nuget push "dist/*.nupkg" --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json
